### ISSUE TITLE
'Cannot be updated' warning

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/tagadelic#30]
I'm getting this warning when trying to update my database for a core update:

> tagadelic module can not be updated. Its schema version is 1000. Updates up to and including 6100 have been removed in this release. In order to update tagadelic module, you will first need to upgrade to the last version in which these updates were available.

**Comment by indigoxela** [comment]
Same here.

See also: https://github.com/backdrop/backdrop-issues/issues/2565

I belief, this part can be safely removed:

```
/**
 * Implements hook_update_last_removed().
 */
function tagadelic_update_last_removed() {
  return 6100;
}
```
We don't care about D6 to D7 upgrades.

**Comment by jenlampton** [comment]
pushed a commit for this.
